### ISSUE TITLE
The zip file in Baidu cloud disk may be corrupted

### ISSUE THREAD

**Issue by zhangzc21** [semchan/UPST-NeRF#1]
Sorry to bother you. 

I try to utilize the pre-trained models provided in the [link](https://pan.baidu.com/s/1UxZqCiJIsL94jVonqadEFA). After the download was completed, I attempt to unzip the ZIP file, but it shows that the file was corrupted. I repeated it several times, and the results are same.

By the way, I used a Windows computer to do above process. Could you please confirm whether the uploaded file is complete? Thanks a lot!

**Comment by semchan** [comment]
> 

Sorry for that. I have updated the link and fixed this issue, please download from here: [link](https://pan.baidu.com/s/1wtts1bYvmdn4NDRj98JUsA )
[Extracted code]：1234

**Comment by semchan** [comment]
> 

Sorry for that. I have updated the link and fixed this issue, please download from here: [](https://pan.baidu.com/s/1wtts1bYvmdn4NDRj98JUsA )
[Extracted code]：1234
